version: "3.8"
services:
  test-app:
    image: bassind/nir-test-app
    ports:
      - "8080:8080"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 20s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 10s
    stop_grace_period: 3s