kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8081
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8082
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8083
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8084
    listenAddress: "127.0.0.1"
    protocol: TCP